name: Release Archive

on:
  push:
    branches: [ "release" ]
    
env:
  MARKET_VERSION: 0.0.3
    
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.P12_KEY2 }}
          P12_PASSWORD: ""
          KEYCHAIN_PASSWORD: ""
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.PROV }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.provisionprofile
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          
          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          echo "MARKET_VERSION={{0.0.4}}" >> $GITHUB_ENV
          
      - name: Store credentials
        env:
          APPPASS: ${{ secrets.APP_PASS }}
          DEVID: ${{ secrets.DEV_ID }}
        run: xcrun notarytool store-credentials "AC_PASSWORD" --password "$APPPASS" --apple-id "$DEVID" --team-id 26TL3CY23Q 

      - name: Archive
        run: xcodebuild -project Taihen/Taihen.xcodeproj archive -scheme Taihen -archivePath ArchiveResults/Taihen.xcarchive

      - name: Export for Notary
        run: xcodebuild -project Taihen/Taihen.xcodeproj -exportArchive -archivePath ArchiveResults/Taihen.xcarchive -exportPath ExportArchive/Taihen.archive -exportOptionsPlist Taihen/NoSignExportOptions.plist

      - name: Export Archive results
        uses: actions/upload-artifact@v3
        with:
          name: appUnsigned
          path: ExportArchive/Taihen.archive

      - name: Zip Folder
        run: /usr/bin/ditto -c -k --keepParent ExportArchive/Taihen.archive Taihen.zip

      - name: Create App Folder
        run: |
            mkdir Taihen_${{env.MARKET_VERSION}}

      - name: Copy App to Folder
        run: |
            cp -R ExportArchive/Taihen.archive/Taihen.app Taihen_${{env.MARKET_VERSION}}/Taihen.app

      - name: Zip App
        run: |
            /usr/bin/ditto -c -k --keepParent Taihen_${{env.MARKET_VERSION}} TaihenApp.zip

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: Taihen_{{env.MARKET_VERSION}}
          path: TaihenApp.zip

      - name: Upload to notary
        run: xcrun notarytool submit TaihenApp.zip --keychain-profile "AC_PASSWORD" --wait
