name: UnitTestRunner

on: push

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: xcodebuild -project Taihen/Taihen.xcodeproj test -scheme Taihen
